eLearnApps/Controllers/CommonController.cs
using System;
using System.Net;
using eLearnApps.Business;
using eLearnApps.Business.Interface;
using eLearnApps.Core.Caching;
using eLearnApps.CustomAttribute;
using eLearnApps.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;

namespace eLearnApps.Controllers
{
    [Authorize]
    [TrackingLog]
    public class CommonController : BaseController
    {
        private readonly ClaimHelper _claimHelper;
        private readonly IWebHostEnvironment _env;
        private readonly IConfiguration _configuration;
        public CommonController(IWebHostEnvironment env, ICacheManager cacheManager, IErrorLogService errorLogService, IHttpContextAccessor httpContextAccessor, IConfiguration configuration, IServiceProvider serviewProvider, ICompositeViewEngine viewEngine) : base(cacheManager, errorLogService, httpContextAccessor, configuration, serviewProvider, viewEngine)
        {
            _claimHelper = new ClaimHelper(serviewProvider);
            _env = env;
            _configuration = configuration;
        }

        [HttpGet]
        public IActionResult GetUserGuideLink(string toolId)
        {
            var enrollment = _claimHelper.GetEnrollmentFromCache(UserInfo.UserId, CourseId);

            var isStudent = string.Equals(enrollment.RoleName, RoleName.Student.ToString(), StringComparison.InvariantCultureIgnoreCase);
            string path = string.Empty;
            toolId = string.IsNullOrWhiteSpace(toolId) ? "ffts" : toolId.ToLower();
            switch (toolId)
            {
                case "rpt":
                    if (isStudent)
                        path = "https://smu.sharepoint.com/sites/iits/elearnsupport/Documents/student/userguides/MyResults-StudentUserGuide.pdf";
                    else
                        path = "https://smu.sharepoint.com/sites/iits/elearnsupport/Documents/faculty_staff/userguides/ResultsProcessingTool-FacultyUserGuide.pdf";
                    break;

                case "cmt":
                    if (isStudent)
                        path = "https://smu.sharepoint.com/sites/iits/elearnsupport/Documents/student/userguides/MyAttendance-StudentUserGuide.pdf";
                    else
                        path = "https://smu.sharepoint.com/sites/iits/elearnsupport/Documents/faculty_staff/userguides/ClassManagementTool-FacultyUserGuide.pdf";
                    break;

                case "journal":
                    if (isStudent)
                        path = "https://smu.sharepoint.com/sites/iits/elearnsupport/Documents/student/userguides/Journal-StudentUserGuide.pdf";
                    else
                        path = "https://smu.sharepoint.com/sites/iits/elearnsupport/Documents/faculty_staff/userguides/Journal-FacultyUserGuide.pdf";
                    break;

                case "pet":
                    if (isStudent)
                        path = "https://smu.sharepoint.com/sites/iits/elearnsupport/Documents/student/userguides/PeerEvaluationTool-StudentUserGuide.pdf";
                    else
                        path = "https://smu.sharepoint.com/sites/iits/elearnsupport/Documents/faculty_staff/userguides/PeerEvaluationTool-FacultyUserGuide.pdf";
                    break;
                case "ee":
                    var externalUrl = _configuration.GetValue<string>("UserGuideDownloadUrl");
                    if (string.IsNullOrEmpty(externalUrl))
                    {
                        var userGuideRelativePath = "guide/EE_Instructor_UserGuide.pdf";
                        var userGuideFullPath = Path.Combine(_env.WebRootPath, "Content", userGuideRelativePath);

                        if (System.IO.File.Exists(userGuideFullPath))
                        {
                            path = Url.Content($"~/Content/{userGuideRelativePath}");
                        }
                    }
                    else
                    {
                        path = externalUrl;
                    }
                    break;
                default:
                    path = GetDefaultPath(isStudent, toolId);
                    break;
            }

            return Json(path);
        }

        private string GetDefaultPath(bool isStudent, string prefix)
        {
            string path = string.Empty;

            var fileName = isStudent
                ? $"{prefix}_Student_UserGuide.pdf"
                : $"{prefix}_Instructor_UserGuide.pdf";

            var relativePath = Path.Combine("Content", "guide", fileName);
            var fullPath = Path.Combine(_env.WebRootPath, relativePath);

            if (System.IO.File.Exists(fullPath))
            {
                // Ensure path uses forward slashes
                path = Url.Content($"~/{relativePath.Replace("\\", "/")}");
            }

            return path;
        }
    }
}

eLearnApps/Controllers/EEController.cs
using eLearnApps.Business.Interface;
using eLearnApps.Core;
using eLearnApps.Core.Caching;
using eLearnApps.CustomAttribute;
using eLearnApps.Entity.Logging;
using eLearnApps.Entity.Security;
using eLearnApps.Valence;
using eLearnApps.Helpers;
using eLearnApps.ViewModel.Valence;
using System.IO.Compression;
using System.Text;
using System.Web.Hosting;
using OrgUnitUser = eLearnApps.Entity.Valence.OrgUnitUser;
using System.Text.RegularExpressions;
using System.Net.Http.Headers;
using eLearnApps.Entity.Logging.Dto;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.AspNetCore.Mvc;
using System.Xml;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System.Text.Json;
using Microsoft.AspNetCore.Hosting;
using eLearnApps.ViewModel.EE;
using eLearnApps.Models;
using eLearnApps.Models.GptZeroModels;

namespace eLearnApps.Controllers
{
    [Authorize, TrackingLog]
    public class EEController : BaseController
    {
        private readonly ICourseService _courseService;
        private readonly IIcsService _icsService;
        private readonly ICmtService _cmtService;
        private readonly IUserService _userService;
        private readonly ILoggingService _loggingService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IConfiguration _configuration;
        private readonly IServiceScopeFactory _serviceScopeFactory;

        private readonly Constants _constants;

        private readonly string[] sizes = new string[4] { "10", "11", "12", "14" };
        private readonly string[] spaces = new string[4] { "1.0", "1.15", "1.5", "2.0" };

        readonly ValenceApi vapi;

        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private static List<char> allowedCharacters = new List<char>("1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz.{}:\\\"");

        public EEController(IIcsService icsService,
            ICourseService courseService,
            ICmtService cmtService,
            ILoggingService loggingService,
            IUserService userService,
            ICacheManager cacheManager,
            IHttpContextAccessor httpContextAccessor,
            IConfiguration configuration,
            IServiceProvider serviewProvider,
            ICompositeViewEngine compositeViewEngine,
            IWebHostEnvironment webHostEnvironment,
            IErrorLogService errorLogService,
            IServiceScopeFactory serviceScopeFactory) : base(cacheManager, errorLogService, httpContextAccessor, configuration, serviewProvider, compositeViewEngine)
        {
            _icsService = icsService;
            _courseService = courseService;
            _cmtService = cmtService;
            _userService = userService;
            _loggingService = loggingService;
            _webHostEnvironment = webHostEnvironment;
            _constants = new Constants(configuration);
            _configuration = configuration;
            vapi = new ValenceApi(configuration);
            _serviceScopeFactory = serviceScopeFactory;
        }
        [HttpGet, ClaimRequirement(nameof(StandardPermissionProvider.ManageExtraction))]
        public IActionResult Index()
        {
            var userGuideRelativePath = "~/Content/guide/EE_Instructor_UserGuide.pdf";
            string userGuideFilePath = Path.Combine(_webHostEnvironment.WebRootPath, userGuideRelativePath.TrimStart('/'));

            if (System.IO.File.Exists(userGuideFilePath))
            {
                ViewBag.UserGuide = Url.Content(userGuideRelativePath);
            }
            return View();
        }

        [HttpGet, ClaimRequirement(nameof(StandardPermissionProvider.ManageExtraction))]
        public IActionResult _Options()
        {
            //get grade object id
            var quizObjects = vapi.GetQuizObjectsByCourseId(CourseId);
            LogDebug("examextraction-_options: GetQuizObjectsByCourseId", $"{CourseId}");

            LogDebug("examextraction-_options: inspect quiz objects return by WS", $"{JsonSerializer.Serialize(quizObjects)}");

            var quizzes = new List<SelectListItem>();

            // Auto-select the last item on the list
            int i = 1;
            foreach (var quiz in quizObjects.Objects.ToList())
            {
                quizzes.Add(new SelectListItem()
                {
                    Text = quiz.Name,
                    Value = quiz.QuizId.ToString(),
                    Selected = i == quizObjects.Objects.ToList().Count() ? true : false
                });

                LogDebug("examextraction-_options: Added quiz as a select item", $"Text:{quiz.Name}, Value:{quiz.QuizId.ToString()}, Index:{i}");
                i++;
            }

            LogDebug("examextraction-_options: inspect final selectlist", $"{JsonSerializer.Serialize(quizzes)}");
            var fontSizes = new List<SelectListItem>();
            var lineSpaces = new List<SelectListItem>();

            foreach (var size in sizes)
            {
                fontSizes.Add(new SelectListItem()
                {
                    Text = size.ToString(),
                    Value = size.ToString(),
                    Selected = size == "11" ? true : false
                });
            }

            foreach (var space in spaces)
            {
                lineSpaces.Add(new SelectListItem()
                {
                    Text = space.ToString(),
                    Value = space.ToString(),
                    Selected = space == "1.15" ? true : false
                });
            }
            var sections = new List<SelectListItem>();
            sections.AddRange(vapi.GetSectionByCourseId(CourseId)?.Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.SectionId.ToString(),
            }).ToList() ?? new List<SelectListItem>());
            if (sections.Count > 1)
            {
                sections.Insert(0, new SelectListItem
                {
                    Value = "",
                    Text = "All"
                });
            }

            var vm = new CreateExtractionViewModel
            {
                Quizzes = quizzes,
                FontSizes = fontSizes,
                Sections = sections,
                LineSpaces = lineSpaces,
                CourseId = CourseId,
                EnableGPTZeroOption = _constants.EnableGPTZeroOption,
                QuestionTypes = GetQuestionType()
            };

            LogDebug("examextraction-_options: inspect return vm", $"{JsonSerializer.Serialize(vm)}");

            return PartialView("_Options", vm);
        }

        [HttpPost]
        [ClaimRequirement(nameof(StandardPermissionProvider.ManageExtraction))]
        [ValidateAntiForgeryToken]
        [DeleteFile]
        public async Task<ActionResult> CreateExtraction(CreateExtractionViewModel model)
        {
            if (string.IsNullOrWhiteSpace(model.FontSize) || !sizes.Contains(model.FontSize))
                model.FontSize = sizes.First();

            if (string.IsNullOrWhiteSpace(model.LineSpace) || !spaces.Contains(model.LineSpace))
                model.LineSpace = spaces.First();

            LogDebug("examextraction-createextraction: inspect viewmodel", $"{JsonSerializer.Serialize(model)}");

            bool isValidQuiz = int.TryParse(model.QuizId, out int quizId);

            if (!isValidQuiz)
                return Json("");

            if (model.GroupBy == (int)ExamExtractionGroupBy.Question)
            {
                model.IsQuestionShown = true;
                model.ExportOption = (int)ExportOption.AllToOneDocument;
            }

            // Get section(s) info
            var sections = GetSectionsByCourseId(model.CourseId, model.SortBy);

            LogDebug("examextraction-createextraction: inspect sections", $"{JsonSerializer.Serialize(sections)}");

            List<UserResponse> allResponses = new List<UserResponse>();

            StringBuilder sbTextResponse = new StringBuilder();
            // Loop over each section and over each user to get their responses
            var listUserResponse = new List<UserResponse>();
            var studentAnswers = new Dictionary<int, string>();
            //var isFirst = true;
            foreach (var section in sections)
            {
                LogDebug("examextraction-createextraction: inspect section.Enrollments", $"{JsonSerializer.Serialize(section.Enrollments)}");

                foreach (var userIds in section.Enrollments)
                {
                    var quizResponse = vapi.GetQuizResponseByUserId(model.CourseId, quizId, userIds);
                    quizResponse.SectionName = string.IsNullOrEmpty(section.Name) ? string.Empty : section.Name;
                    //if (isFirst)
                    //{
                    //    isFirst = false;
                    //    quizResponse.Responses[0].TextResponse = @"<span color: yellow>The environment is the foundation of life on Earth, encompassing the air we breathe, the water we drink, the land we inhabit, and the ecosystems that sustain us. As our global population continues to grow and industrialization accelerates, the strain on our natural resources and ecosystems has reached alarming levels. Protecting the environment is not just a matter of preserving natural beauty; it is essential for our survival and the well-being of future generations. </span>
                    //Diners who are keen to buy unsold food from eateries at up to 80 per cent off the retail price before closing time, instead of letting it go to waste, can tap a new mobile phone application.
                    //<b>1. Human activities, particularly over the last century, have led to significant environmental degradation. </b>

eLearnApps/Controllers/MenuController.cs
using eLearnApps.Business.Interface;
using eLearnApps.Core.Caching;
using eLearnApps.CustomAttribute;
using eLearnApps.ViewModel.KendoUI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.Extensions.DependencyInjection;
using System.Configuration;

namespace eLearnApps.Controllers
{
    [Authorize, TrackingLog]
    public class MenuController : BaseController
    {
        private readonly ISemesterService _semesterService;
        private readonly ICourseService _courseService;
        public MenuController(
        ISemesterService semesterService,
        ICourseService courseService,
        ICacheManager cacheManager,
          IHttpContextAccessor httpContextAccessor,
            IConfiguration configuration,
             IServiceProvider serviewProvider,
            ICompositeViewEngine compositeViewEngine,
            IErrorLogService errorLogService) : base(cacheManager, errorLogService, httpContextAccessor, configuration, serviewProvider, compositeViewEngine)
        {
            _courseService = courseService;
            _semesterService = semesterService;
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> PopulateDropdown(int? semesterId)
        {
            var semesters = await _semesterService.GetAllByUserIdAsync(UserInfo.UserId);
            var result = semesters.Select(x => new TreeViewItem
            {
                id = x.Id,
                text = x.Name,
                hasChildren = true,
                expanded = x.Id == semesterId.Value,
            }).OrderByDescending(s => s.id).ToList();
            return Json(result);
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> GetBySemesterId(int? semesterId)
        {
            var lstCourse = new List<Entity.LmsTools.Course>();
            if (semesterId.HasValue)
            {
                lstCourse = await _courseService.GetBySemesterIdAsync(UserInfo.UserId, semesterId.Value);
            }
            return Json(lstCourse.Select(x => new NodeItem
            {
                id = x.Id,
                text = x.Name
            }).OrderByDescending(item => item.id).ToList());
        }
    }

}

eLearnApps/Views/Shared/_AppJs.cshtml
@{
   var controllerName = ViewContext.RouteData.Values["controller"].ToString();
    if (string.Compare(controllerName, FunctionName.Journal.ToString(), StringComparison.OrdinalIgnoreCase) == 0)
    {
        <script src="~/Scripts/ckeditor/ckeditor.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
        <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js"></script>
        <script>
            const ViewType = {  List: 'List', Grid: 'Grid', Group: 'Group' }
        </script>
    }
}

eLearnApps/Views/Shared/_Header.cshtml
<style>
    #dvTermCourse {
        font-weight: 500;
    }
</style>
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "_headerform" }))
{
    @Html.AntiForgeryToken()
    <div id="section-not-print" class="navbar navbar-expand-lg navbar-dark bg-header d-flex flex-wrap justify-content-between sticky-top navbar pt-0 pb-0 mb-6">
        <div class="order-xl-1">
            <div class="d-flex">
                <div class="flex-fill">
                    <button class="navbar-toggle-always sidebar-toggler  d-lg-none mr-auto " type="button" data-toggle="sidebar-show">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <button class="navbar-toggle-always sidebar-toggler d-md-down-none mr-auto " type="button" data-toggle="sidebar-lg-show">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="flex-fill nav navbar-nav">
                    <span class="nav-link">
                        <span class="" id="lblFormTitle">
                            @if (ViewBag.PageIcon == null)
                            {
                                <i class="nav-icon icon-calendar"></i>
                                <span>&nbsp; @ViewBag.Title</span>
                            }
                            else
                            {
                                <img src="@ViewBag.PageIcon" width="35" height="35">
                                <span class=" d-md-down-none">@ViewBag.Title</span>
                            }
                        </span>
                    </span>
                </div>
            </div>
        </div>
        <div class="order-xl-3 ml-auto">
            <div class="d-flex">
                <div class="flex-fill">

                    <a class="nav-link mt-2" id="lnkUserGuideNoLink" title="User Guide" style="display: none;">
                        <i class="fa fa-question-circle fa-2x" style="color: lightgray;"></i>
                    </a>

                    <a class="nav-link mt-2" title="User Guide" id="lnkUserGuide" style="color: white; display: none;" download target="_blank">
                        <i class="fa fa-question-circle fa-2x"></i>
                    </a>
                </div>
                <div class=" flex-fill">
                    <a class="nav-link" href="https://www.smu.edu.sg/">
                        <img src="@Url.Content("~/Content/images/logo.png")" width="100" height="39" alt="SMU Logo" />
                    </a>
                </div>
            </div>
        </div>
        <div class=" order-xl-2 flex-grow-1">
            <div class="d-md-flex flex-md-row justify-content-center">
                <div class="col-11">
                    <div class="d-flex">
                        <div class="p-2 flex-fixed-width-item ">
                            <label for="term" class="pt-2 font-weight-bold">TERM/COURSE</label>
                        </div>
                        <div class="p-2 flex-grow-1" id="dvTermCourse">
                            <input id="termCourse" placeholder="Select term/course..." style="width: 100%;" class="form-control" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script>
    const urlDropdown = '@Url.Action("PopulateDropdown", "Menu", new {CourseID = ViewBag.CourseId})';
    const urlBySemester = '@Url.Action("GetBySemesterId", "Menu", new {CourseID = ViewBag.CourseId})';
    var selectedCourseId = parseInt(@ViewBag.CourseId);
    window.courseId = selectedCourseId;
    var selectedTermId = parseInt(@ViewBag.TermId);
    const GetBySemesterAsync = async (id) => {
        let result = await createPostRequest(urlBySemester, { semesterId: id });
        return result;
    }
    const prepareDropdown = async () => {
        let datasource = new kendo.data.HierarchicalDataSource({
            transport: {
                read: function (options) {
                    createPostRequest(urlDropdown, { semesterId: selectedTermId }).then(function (datasource) {
                        options.success(datasource);
                    });
                }
            },
            schema: {
                model: {
                    id: "id",
                    hasChildren: true,
                    children: {
                        transport: {
                            read: function (options) {
                                createPostRequest(urlBySemester, { semesterId: options.data.id }).then(function (datasource) {
                                    options.success(datasource);
                                });
                            }
                        },
                        schema: {
                            model: {
                                id: "id",
                                hasChildren: false
                            }
                        }
                    }
                }
            }
        });
        $("#termCourse").kendoDropDownTree({
            placeholder: "Select ...",
            filter: "contains",
            autoWidth: true,
            dataTextField: "text",
            dataValueField: "id",
            clearButton: false,
            value: selectedCourseId,
            dataSource: datasource,
            loadOnDemand: true,
            select: function (e) {
                let item = e.sender.dataItem(e.node);
                if (item.hasChildren) {
                    e.preventDefault();
                    let cbo = $("#termCourse").data("kendoDropDownTree");
                    let treeview = cbo.treeview;
                    treeview.collapse(".k-item");
                    treeview.expand(treeview.findByUid(item.uid));
                    treeview.expandTo(item.Id);
                }
            },
            change: function (e) {
                selectedCourseId = e.sender.value();
                window.courseId = selectedCourseId;
                updateClaim();
            }
        }).data("kendoDropDownTree");
    }
    $(document).ready(function() {
        window.kendo.init("#buttonContainer");
        GetUserGuide();
        prepareDropdown();
    });

    var controllerName = "@ViewContext.RouteData.Values["controller"]?.ToString()";

    let urlGetGuideLink = `@Url.Action("GetUserGuideLink", "Common")?CourseId=@(ViewBag.CourseId)&toolId=${controllerName}`;
    const GetUserGuide = async () => {
        const response = await ExecuteWithOutHeader(urlGetGuideLink, HttpMethod.GET);
        if (response !== null && response !== undefined && response.length > 0) {
            $('#lnkUserGuide').attr('href', response);
            $('#lnkUserGuide').show();
        } else {
            $('#lnkUserGuideNoLink').show();
        }
    };
    $('#sidebar_toggle').click(function() {
        setTimeout(function() { $(window).trigger('resize'); }, 300);
    });

    const updateClaim = () => {
        const url = `@Url.Action("UpdateClaims", "Account")?courseId=${selectedCourseId}&hash=${window.location.hash.replace("#", "")}&referrer=${window.location}`;
        createPostRequest(url).then(function (response) {
            if (response.redirectUrl) {
                window.location = response.redirectUrl;
            }
        });
    };
</script>
<style>
    .flex-fixed-width-item {
        flex: 0 0 70px;
    }

    .navbar-toggle-always {
        background-color: transparent;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 4px;
        float: right;
        margin-bottom: 8px;
        margin-left: 0;
        margin-right: 15px;
        margin-right: 0;
        margin-top: 8px;
        padding: 9px 10px;
        position: relative;
    }

        .navbar-toggle-always:focus {
            outline: 0;
        }
</style>

eLearnApps/Views/Shared/_LayoutClean.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="Find Free Time Slots">
    <meta name="keyword" content="SMU">
    <link rel="shortcut icon" href="@Url.Content("~/Content/appsicon/favicon.ico")" type="image/x-icon" />
    <title>@ViewBag.Title</title>
    <!-- Icons-->
    <script src="~/Scripts/CoreUI/vendors/jquery/js/jquery.min.js"></script>
    <link href="~/Scripts/CoreUI/vendors/@Html.Raw("@coreui")/icons/css/coreui-icons.min.css" rel="stylesheet">
    <link href="~/Scripts/CoreUI/vendors/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">
    <link href="~/Scripts/CoreUI/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Scripts/CoreUI/vendors/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">
    <!-- Main styles for this application-->
    <link href="~/Scripts/CoreUI/css/style.css" rel="stylesheet">
    <link href="~/Scripts/CoreUI/vendors/pace-progress/css/pace.min.css" rel="stylesheet">
    <link href="@Url.Content("~/Content/kendo/kendo.common-material.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/kendo.mobile.all.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/kendo.material.min.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/kendo/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/jszip.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/kendo.all.min.js")"></script>
    <!-- Custom Style-->
    <link href="@Url.Content("~/Content/customStyle.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/moment.js")"></script>
    <script src="@Url.Content("~/Scripts/moment-timezone-with-data.js")"></script>
    <script src="@Url.Content("~/Scripts/Common.js")"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js"></script>


    <script>
        var CourseId;
        var detect = jstz.determine();
        var TimeZone = detect.name();
    </script>

</head>
<body class="app flex-row align-items-center">
    <div class="app-body">
        <main class="main">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </main>
    </div>
    <script src="~/Scripts/CoreUI/vendors/popper.js/js/popper.min.js"></script>
    <script src="~/Scripts/CoreUI/vendors/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/CoreUI/vendors/@Html.Raw("@coreui")/coreui/js/coreui.min.js"></script>
</body>
</html>

eLearnApps/Views/Shared/_LeftMenuEE.cshtml
@using System.Security.Claims
@using eLearnApps.Entity.Security
@using eLearnApps.Extension
@inject IServiceProvider ServiceProvider
@{
    var extensions = new Extensions(ServiceProvider);
}
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav" id="leftMenu">


            @if (extensions.HasClaim(User.Identity, nameof(StandardPermissionProvider.ManageExtraction)))
            {
                <li class="nav-item">
                    <a id="icsHome" tag="#index" class="nav-link" href="@Url.Action("_Options", "EE", new { courseId = Context.Request.Query["courseId"] })">
                        <i class="nav-icon icon-home"></i> Exam Extraction
                    </a>
                </li>
            }


        </ul>
    </nav>
</div>

<script type="text/javascript">

    $(function () {
        console.log("Version: @ViewBag.GitHash");

        const courseDropdown = $("#course").data("kendoDropDownList");

        if (window.location.hash === "") {
            const first = $("#leftMenu li a.nav-link").first();
            $("a.nav-link").removeClass("active");
            first.addClass("active");
            window.location.hash = first.attr("tag");
            Navigate(first.attr("href"));
        } else {
            var current = location.href;

            $("#leftMenu li a.nav-link").each(function () {
                const tag = $(this).attr("tag");
                // if the current path is like this link, make it active
                if (current.indexOf(tag) !== -1) {
                    const url = $(this).attr("href");
                    $("a.nav-link").removeClass("active");
                    $(this).addClass("active");
                    window.location.hash = tag;
                    Navigate(url);
                }
            });
        }

        $("#leftMenu li a.nav-link").click(function (e) {
            e.preventDefault();
            const url = $(this).attr("href");
            const tag = $(this).attr("tag");
            $("a.nav-link").removeClass("active");
            $(this).addClass("active");
            window.location.hash = tag;
            Navigate(url);
        });

        function Navigate(url) {
            $("#main").html('');
            $("#main").load(url, function () {
            });
        }
    });

</script>