eLearnApps/Models/PeerFeedback/AuditActionModel.cs
namespace eLearnApps.ViewModel.PeerFeedback
{
    public class AuditActionModel
    {
        public string Question { get; set; }
        public AuditResourceId ResourceId { get; set; }
        public int CourseId { get; set; }
    }
}

eLearnApps/Models/PeerFeedback/ExportGroupReadinessReportRequestModel.cs
using System.Collections.Generic;

namespace eLearnApps.Models.PeerFeedback
{
    public class ExportGroupReadinessReportRequestModel
    {
        public string TimeZone { get; set; } = "Asia/Singapore";
        public List<string> Terms { get; set; } = new List<string>();
    }
}

eLearnApps/Models/PeerFeedback/ExportParticipatingCourseCsvModel.cs
using CsvHelper.Configuration.Attributes;

namespace eLearnApps.Models.PeerFeedback
{
    public class ExportParticipatingCourseCsvModel
    {
        [Name("Offering School")]
        public string AcadGroup { get; set; }

        [Name("Course Code")]
        public string CourseCode { get; set; }

        [Name("Course Title")]
        public string CourseName { get; set; }

        [Name("Instructor")]
        public string Instructor { get; set; }

        [Name("Total Participants")]
        public int StudentCount { get; set; }

        [Name("Group Names")]
        public string GroupNames { get; set; }

        [Name("Number of Groups")]
        public int GroupCount { get; set; }

        [Name("Unassigned Student Count")]
        public int UnassignedStudentCount { get; set; }

        [Name("Has Multiple Group (Y/N)")]
        public string HasMultipleGroup { get; set; }

        [Name("Duplicate Enrolment (Y/N)")]
        public string Duplicates { get; set; }

        [Name("Created In PSFS")]
        public string CreatedInPSFS { get; set; }
    }
}

eLearnApps/Models/PeerFeedback/ExportPeerFeedBackToExcelModel.cs
namespace eLearnApps.Models.PeerFeedback
{
    public class ExportPeerFeedBackToExcelModel
    {
        
        public List<int> Sessions { get; set; }

        /// <summary>
        /// 0 - Group by Course/Section, 1 - Group by Student School
        /// </summary>
        
        public PeerFeedBackReportGroupBy GroupBy { get; set; }

        /// <summary>
        /// 0 - Overall Response Rate
        /// 1 - Overall Descriptor Result
        /// 2 - Overall MEAN Score Result
        /// 3 - Individual Student Result
        /// </summary>
        
        public PeerFeedBackReportType ReportType { get; set; }
        public string TimeZone { get; set; } = "Asia/Singapore";
        public string SessionNames { get; set; }
    }
}

eLearnApps/Models/PeerFeedback/StudentPeerFeedbackViewModel.cs
namespace eLearnApps.Models.PeerFeedback
{
    public class StudentPeerFeedbackViewModel
    {
        public UserModel UserInfo { get; set; }
        public bool HasClosedSession { get; set; }
        public bool IsInitialLanding { get; set; }
    }
    public class PeerFeedBackResponseEvaluatorTargetModel
    {
        public int EvaluatorUserId { get; set; }
        public int TargetUserId { get; set; }
    }
    public class PeerFeedBackSessionGroupModel
    {
        public int PeerFeedBackId { get; set; }
        public int PeerFeedBackSessionId { get; set; }
        public int PeerFeedBackGroupId { get; set; }
        public int PeerFeedBackQuestionId { get; set; }
        public int EvaluatorUserId { get; set; }
    }
}

eLearnApps/Controllers/PeerFeedbackController.cs
using eLearnApps.Business.Interface;
using eLearnApps.Core;
using eLearnApps.Core.Caching;
using eLearnApps.Core.Extension;
using eLearnApps.CustomAttribute;
using eLearnApps.Entity.LmsTools;
using eLearnApps.Entity.LmsTools.Dto;
using eLearnApps.Entity.Logging;
using eLearnApps.Extension;
using eLearnApps.Helpers;
using eLearnApps.Models;
using eLearnApps.Models.PeerFeedback;
using eLearnApps.ViewModel.KendoUI;
using eLearnApps.ViewModel.PeerFeedback;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using TimeZoneConverter;
using Extensions = eLearnApps.Extension.Extensions;

namespace eLearnApps.Controllers
{
    public class PeerFeedbackController : BaseNoCourseController
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private readonly Constants _constants;
        private readonly Extensions _extensions;
        private readonly IWebHostEnvironment _env;
        private readonly IServiceProvider _serviceProvider;
        #region CTOR

        public PeerFeedbackController(
            ICourseService courseService,
            IUserService userService,
            ICacheManager cacheManager,
            IHttpContextAccessor httpContextAccessor,
            IConfiguration configuration,
            IServiceProvider serviceProvider,
            ICompositeViewEngine compositeViewEngine,
            IWebHostEnvironment webHostEnvironment,
            IErrorLogService errorLogService,
            IPeerFeedbackService peerFeedbackService,
            ISemesterService semesterService,
            IUserEnrollmentService userEnrollmentService,
            ICategoryGroupService categoryGroupService,
            ICourseCategoryService courseCategoryService,
            IWebHostEnvironment env,
            ILoggingService loggingService,
            ICurrentUserService currentUserService,
            IUserGroupService userGroupService, IValenceService valenceService,
            IAuditService auditService) : base(cacheManager, errorLogService, serviceProvider, configuration, httpContextAccessor, currentUserService)
        {
            _courseService = courseService;
            _userService = userService;
            _semesterService = semesterService;
            _peerFeedbackService = peerFeedbackService;
            _categoryGroupService = categoryGroupService;
            _userEnrollmentService = userEnrollmentService;
            _userGroupService = userGroupService;
            _courseCategoryService = courseCategoryService;
            _constants = new Constants(configuration);
            _extensions = new Extensions(serviceProvider);
            _loggingService = loggingService;
            _auditService = auditService;
            _valenceService = valenceService;
            _serviceProvider = serviceProvider;
            _env = env;
        }

        #endregion

        // GET: PeerFeedback
        public IActionResult Index()
        {
            return View();
        }
        [PeerFeedBackAuthorize(Role = "student")]
        public ActionResult PeerFeedback()
        {
            log.Info("**************** START PeerFeedback ****************");
            // after reading this var, then set it to false
            var isInitialLanding = JsonSerializer.Deserialize<bool>(HttpContext.Session.GetString("IsInitialLanding"));
            log.Info($"IsIsInitialLanding: {isInitialLanding.ToJson()}");
            HttpContext.Session.SetString("IsInitialLanding", "false");

            log.Info("------ start PeerFeedBackEvaluationList ------");
            log.Info($"param: UserId = {UserInfo.UserId}");
            var peerfeedbacks = _peerFeedbackService.PeerFeedBackEvaluationList(UserInfo.UserId);
            log.Info("------ end PeerFeedBackEvaluationList ------");
            log.Info("Check closed Session");
            var HasClosedSession = peerfeedbacks.Any(p => p.To < DateTime.UtcNow);
            log.Info($"HasClosedSession: {HasClosedSession.ToJson()}");

            var vm = new Models.PeerFeedback.StudentPeerFeedbackViewModel()
            {
                UserInfo = UserInfo,
                HasClosedSession = HasClosedSession,
                IsInitialLanding = isInitialLanding
            };
            log.Info("**************** END PeerFeedback ****************");
            return PartialView(vm);
        }
        [PeerFeedBackAuthorize(Role = "student")]
        public ActionResult PeerFeedbackList()
        {
            log.Info("**************** START PeerFeedbackList ****************");
            log.Info("------ start PeerFeedBackEvaluationList ------");
            var result = _peerFeedbackService.PeerFeedBackEvaluationList(UserInfo.UserId);
            log.Info("------ end PeerFeedBackEvaluationList ------");
            var model = new PeerFeedbackListModel();
            var feedBacks = new List<PeerFeedbackViewModel>();
            log.Info("Loop through PeerFeedBackEvaluationList");
            foreach (var item in result)
            {
                double progress = 0; int groupCountComplete = 0;
                log.Info("------ start PeerFeedbackTargetsGetByPairingGroup ------");
                var targets = _peerFeedbackService.PeerFeedbackTargetsGetByPairingGroup(item.PeerFeedBackPairingId, item.PeerFeedBackGroupId);
                log.Info("------ end PeerFeedbackTargetsGetByPairingGroup ------");
                log.Info("------ start PeerFeedBackResponsesGetListByUser ------");
                var allResponses = _peerFeedbackService.PeerFeedBackResponsesGetListByUser(item.PeerFeedBackId, item.PeerFeedBackSessionId, item.PeerFeedBackGroupId, UserInfo.UserId);
                log.Info("------ end PeerFeedBackResponsesGetListByUser ------");
                log.Info("------ start PeerFeedBackResponsesGetList ------");
                var responsesGroup = _peerFeedbackService.PeerFeedBackResponsesGetList(item.PeerFeedBackId, item.PeerFeedBackSessionId, item.PeerFeedBackGroupId).ToList();
                log.Info("------ end PeerFeedBackResponsesGetList ------");
                Dictionary<int, int> dicUserQuestion = new Dictionary<int, int>();

                log.Info("------ start PeerFeedbackQuestionMapList ------");
                var peerFeedBackQuestions = _peerFeedbackService.PeerFeedbackQuestionMapList(item.PeerFeedBackId);
                log.Info("------ end PeerFeedbackQuestionMapList ------");
                double userCompleteCount = 0;
                int userGroupCompleteCount = 0;
                int userCount = targets.Count;
                log.Info("Loop through PeerFeedbackTargets");
                foreach (var user in targets)
                {
                    double questionCompleteCount = 0;
                    questionCompleteCount = allResponses
                            .Where(x => x.TargetUserId == user.UserId)
                            .Select(x => x.PeerFeedbackQuestionId)
                            .Distinct()
                            .Count();
                    var usersWithQuestion = responsesGroup
                       .Where(x => x.EvaluatorUserId == user.UserId)
                       .Select(x => new PeerFeedBackResponses
                       {
                           TargetUserId = x.TargetUserId,
                           PeerFeedbackQuestionId = x.PeerFeedbackQuestionId
                       }).Distinct().ToList();
                    var userGroupCount = usersWithQuestion.Select(x => x.TargetUserId).Distinct().Count();
                    var questionGroupCount = usersWithQuestion.GroupBy(p => p.TargetUserId, p => p.PeerFeedbackQuestionId, (targetUserId, questions) => new { userId = targetUserId, QuestionCount = questions.Distinct().Count() }).Select(x => x.QuestionCount).Sum();

                    if (questionCompleteCount == peerFeedBackQuestions.Count)
                        userCompleteCount++;
                    if (userGroupCount == userCount && questionGroupCount == peerFeedBackQuestions.Count * userCount)
                        userGroupCompleteCount++;
                }
                progress = (userCompleteCount / (targets.Count)) * 100;
                groupCountComplete = userGroupCompleteCount;
                var peerFeedbackViewModel = new PeerFeedbackViewModel
                {
                    Name = item.CourseName,
                    Label = item.Name,
                    EntryStartTime = item.From,
                    EntryCloseTime = item.To,
                    Progress = progress,
                    GroupCountComplete = groupCountComplete,
                    TotalUserCountInGroup = targets.Count,
                    PeerFeedBackGroupId = item.PeerFeedBackGroupId,
                    PeerFeedBackPairingId = item.PeerFeedBackPairingId,
                    PeerFeedBackSessionId = item.PeerFeedBackSessionId,
                    PeerFeedBackId = item.PeerFeedBackId,
                    SessionName = item.SessionName,
                    PeerFeedBackKey = _extensions.ToEncrypt(item.PeerFeedBackId)
                };
                feedBacks.Add(peerFeedbackViewModel);
            }
            log.Info("data fulfilled list entity responses");
            model.PeerFeedbacks = feedBacks;
            log.Info("**************** END PeerFeedbackList ****************");
            return PartialView(model);
        }
        [PeerFeedBackAuthorize(Role = "student")]

eLearnApps/Controllers/SelfDirectedLearningResourcesViewComponent.cs
using eLearnApps.Entity.LmsTools;
using eLearnApps.ViewModel.PeerFeedback;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace eLearnApps.Controllers
{
    public class SelfDirectedLearningResourcesViewComponent : ViewComponent
    {
        private static readonly log4net.ILog _log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private readonly Constants _constants;
        private readonly IWebHostEnvironment _env;
        public SelfDirectedLearningResourcesViewComponent(
            IWebHostEnvironment env,
            IConfiguration configuration,
            ILogger<SelfDirectedLearningResourcesViewComponent> log)
        {
            _constants = new Constants(configuration);
            _env = env;
        }
        public async Task<IViewComponentResult> InvokeAsync(string resourceId, string questionTitle)
        {
            _log.Info("**************** START SelfDirectedLearningResources ****************");

            var model = new SelfDirectedLearningResourcesModel();
            //var templateFile = $"{Server.MapPath(_constants.StaticFilesFolder)}/SelfDirectedLearningResources.json";
            var templateFile = Path.Combine(_env.WebRootPath, _constants.StaticFilesFolder, "SelfDirectedLearningResources.json");
            var content = System.IO.File.ReadAllText(templateFile);
            if (!string.IsNullOrEmpty(content))
            {
                _log.Info("json convert to List<SelfDirectedLearningResourcesModel>");
                var items = JsonSerializer.Deserialize<List<SelfDirectedLearningResourcesModel>>(content);
                if (string.Compare(questionTitle, _constants.ResponsibilityQuestionText, true) == 0)
                {
                    model = items.First(x => x.ItemType == 1);
                }
                else if (string.Compare(questionTitle, _constants.MeetsExpectationsQuestionText, true) == 0)
                {
                    model = items.First(x => x.ItemType == 2);
                }
                else if (string.Compare(questionTitle, _constants.ExceedsExpectationsQuestionText, true) == 0)
                {
                    model = items.First(x => x.ItemType == 3);
                }
                model.QuestionName = questionTitle;
                model.ResourceId = resourceId;
            }
            _log.Info("**************** END SelfDirectedLearningResources ****************");
            return View("_SelfDirectedLearningResources", model);
        }
    }
}

eLearnApps/Views/PeerFeedback/Index.cshtml
@{
    ViewBag.Title = "Peer and Self Feedback";
    Layout = "~/Views/Shared/_LayoutPF.cshtml";
    ViewBag.PageIcon = Url.Content("~/Content/appsicon/psfs_logo_bg_blue.png");
}

eLearnApps/Views/PeerFeedback/ManagePeerFeedback.cshtml
@inject IConfiguration Configuration
@{
    ViewBag.Title = "Peer and Self Feedback Tool";
    ViewBag.PageIcon = Url.Content("~/Content/appsicon/psfs_logo_bg_blue.png");
    var constants = new Constants(Configuration);
}
<style>
    .k-grid tbody .k-grid-delete {
        min-width: 0;
    }

        .k-grid tbody .k-grid-delete .k-icon {
            margin: 0;
        }

    #grid .k-grid-header .k-link {
        color: white !important;
    }

    .k-window-titlebar {
        background-color: #0e2669 !important;
        color: white;
    }
</style>
<div>
    <form id="frmManage">
        @Html.AntiForgeryToken()
        <div class="card page-layout">
            <div class="card-header d-flex">
                <h3 class="pl-2 mr-auto">Peer and Self Feedback</h3>
                <button type="button" id="btnAdd" class="k-button k-primary ml-2" onclick="addOrEditPeerFeedback()"><span class="fa fa-plus-circle"></span>&nbsp;Add</button>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-8"></div>
                    <div class="col-4">
                        <span class="k-textbox k-space-left" style="width: 100%;">
                            <input id="txtSearch" type="text" class="icon-left" placeholder="Search condition">
                            <a href="#" class="k-icon k-i-search" id="lnkSearch"></a>
                        </span>
                    </div>
                </div>
                <div class="mt-3" id="grid">
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    function SearchPeerFeedback() {
        const grid = $("#grid").data("kendoGrid");
        let dataSource = grid.dataSource;
        dataSource.filter({ field: "name", operator: "contains", value: $("#txtSearch").val() });
        grid.setDataSource(dataSource);
    }

    function setupInit() {
        $('#lnkSearch').click(function (e) {
            e.preventDefault();
            SearchPeerFeedback();
            return false;
        });
        $('#frmManage').on('keyup keypress',
            function(e) {
                var keyCode = e.keyCode || e.which;
                const target = e.target;
                if (keyCode === 13 && target.id === 'txtSearch') {
                    e.preventDefault();
                    SearchPeerFeedback();
                    return false;
                }
            });
    }
    const getDatasource = () => {
        const url = "@Url.Action("PeerFeedbackGetList", "PeerFeedback")";
        window.kendo.ui.progress($('#grid'), true);
        return createPostRequest(url).then(function (response) {
            window.kendo.ui.progress($('#grid'), false);
            return response;
        });
    }
    const bindGridView = () => {
        getDatasource().then(function (response) {
            const grid = $("#grid").data("kendoGrid");
            if (response && response.data) {
                const source = new window.kendo.data.DataSource({
                   schema: {
                        data: () => response.data,
                        total: () => response.total,
                        errors: () => response.errors,

                    },

                    pageSize: @(constants.PageSize),
                    serverSorting: false
                });
                grid.setDataSource(source);
            }
        });
    }
    $(document).ready(function () {
        $("#grid").kendoGrid({
            sortable: {
                mode: "single",
                allowUnsort: false
            },
            noRecords: true,
            pageable: {
                refresh: true,
                messages: {
                    empty: "No item to display"
                }
            },
            scrollable: true,
            columns: [
                {
                    field: "name",
                    title: "Title",
                    sortable: {
                        initialDirection: "desc"
                    },
                    width: 400
                }, {
                    field: "description",
                    title: "Description",
                    width: 400
                }, {
                    command: [
                        { text: "Edit", click: editPeerFeedback }, { text: "Delete", click: deletePeerFeedback }
                    ],
                    title: "Action",
                    width: 300
                }
            ]
        });
        bindGridView();
        setupInit();
        $('.k-pager-refresh').click(function (e) {
            SearchPeerFeedback();
        });
    });

    function editPeerFeedback(e) {
        e.preventDefault();
        const dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        addOrEditPeerFeedback(dataItem.id);
        return false;
    }

    function deletePeerFeedback(e) {
        const tr = $(e.target).closest("tr"); //get the row for deletion
        var data = this.dataItem(tr); //get the row data so it can be referred later
        e.preventDefault();
        window.kendo.confirm("Are you sure you want to delete the selected?").then(function() {
            const url = `@Url.Action("PeerFeedbackDelete", "PeerFeedback")`;
            const param = { peerFeedbackId: data.id };
            createPostRequest(url, param).then(function(response) {
                $("#grid").data("kendoGrid").removeRow(tr);
                window.kendo.ui.progress($('#grid'), false);
            });
        });
    }
    function addOrEditPeerFeedback(peerFeedbackId) {
        window.kendo.ui.progress($('#grid'), true);
        const url = '@Url.Action("PeerFeedbackCreateOrUpdate", "PeerFeedback")';
        const param = { peerFeedbackId: peerFeedbackId };
        addAntiForgeryToken(param);
        const formData = new FormData();
        buildFormData(formData, param);
        const options = {
            method: 'POST',
            data: formData,
            url: url
        };
        window.axios(options)
            .then(function(result) {
                const response = result.data;
                $("#main").html(response);
                window.kendo.ui.progress($('#grid'), false);
            })
            .catch(function(error) {
                console.log(error);
            });
    }
</script>

eLearnApps/Views/PeerFeedback/_Notice.cshtml
@{
    ViewBag.Title = "_Notice";
}

<h2>_Notice</h2>

eLearnApps/Views/PeerFeedback/_PeerFeedBackResultQuestionStatistic.cshtml
@using eLearnApps.ViewModel.PeerFeedback 
@model eLearnApps.ViewModel.PeerFeedback.PeerFeedBackResultDetailQuestionStatisticViewModel
<style>
    .badge {
        font-size: 100%;
    }
</style>
<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-5">
                <div class="row">
                    <canvas id="chart-@Model.ChartId"></canvas>
                </div>
                @if (Model.RatingQuestion.Count > 0)
                {
                    <div class="row w-100 mt-3">
                        @if (Model.GroupBy == Convert.ToInt32(PeerFeedBackResultGroupBy.AssignedGroup))
                        {
                            <div class="w-100">Total number of ratings received: @Model.CountUserComplete out @Model.TotalUserInGroup group members</div>
                            if (Model.SelfValue != null)
                            {
                                <div class="w-100 mt-3">
                                    My Self Evaluations:<span class="badge me-1 rounded-pill ml-1" style="background-color: @Model.SelfValue.ColorCode !important;color:white;">@Model.SelfValue.Text</span>
                                </div>
                            }
                        }
                        <div class="w-100 mt-3">
                            <button type="button" class="btn btn-lg btn-block k-primary k-button" data-toggle="modal" data-target="#staticBackdrop-@Model.ResourceId">
                                 View Recommended Resources
                            </button>
                            @await Component.InvokeAsync("SelfDirectedLearningResources", new
                                {
                                    resourceId = Model.ResourceId,
                                    questionTitle = Model.QuestionTitle
                                })
                        </div>
                    </div>
                }
            </div>
            <div class="col-7">
                <div class="row w-100">
                    @if (Model.RatingQuestion.Count > 0)
                    {
                        <h5>Overview of descriptors from peers</h5>
                        foreach (var item in Model.RatingQuestion)
                        {
                            if (item.RatingOptions.Count > 0)
                            {
                                <hr class="col-12 w-100" /><br />
                                <div class="col-12 mb-3" style="color: #99979c;"><strong>Descriptor(s) related to @item.Name</strong></div>
                                foreach (var option in item.RatingOptions)
                                {
                                    <div class="col-4">
                                        <div class="progress-group">
                                            <div class="progress-group-header">
                                                <div class="text-muted" style="margin-left: auto !important;">
                                                    <div data-toggle="tooltip" data-placement="top" title="Response rate (@option.Progress.ToString("N2")%) (respondents/ total participants)"><strong>@option.ResponseCount</strong> (@option.Progress.ToString("N2")%)</div>
                                                </div>
                                            </div>
                                            <div class="progress-group-bars">
                                                <div class="progress progress-xs mb-0" style="height:13px;">
                                                    <div class="progress-bar bg-success" style="background-color: @option.ColorCode !important; width: @option.Progress.ToString("N2")%" role="progressbar" aria-valuenow="56" aria-valuemin="0" aria-valuemax="100"></div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-12 text-left"><span class="text-muted">@option.OptionName</span></div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                        }
                    }
                    else
                    {
                        <h5>There is no evaluation record(s) from peers.</h5>
                    }

                </div>
            </div>
        </div>
    </div>
</div>
<script>
    const chartData = @Html.Raw(Model.ChartData);
    var options = {
        plugins: {
            datalabels: {
                formatter: (value, ctx) => {
                    if (value === 0) return '';
                    let datasets = ctx.chart.data.datasets;
                    if (datasets.indexOf(ctx.dataset) === datasets.length - 1) {
                        let sum = datasets[0].data.reduce((a, b) => a + b, 0);
                        let percentage = Math.round(((value / sum) * 100) * 100) / 100 + "%";
                        return `${value} (${percentage})`;
                    } else {
                        return percentage;
                    }
                },
                color: "white"
            }
        }
    };
    $(document).ready(function () {
        const ctx = document.getElementById('chart-@Model.ChartId');
        new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels: chartData.Labels,
                datasets: [{
                    data: chartData.Data,
                    backgroundColor: chartData.BackgroundColor
                }]
            },
            plugins: [ChartDataLabels],
            options: options
        });
        $('[data-toggle="tooltip"]').tooltip();
    });

    $(".btn-show-resource").click(function () {
        const courseId = $('.detail.collapse.show').data('course');
        const url = '@Url.Action("AuditUserAction", "PeerFeedback")';
        const param = {
            ResourceId: 0,
            CourseId: courseId,
            Question: "@Model.QuestionTitle",
        };
        createPostRequest(url, param);
    });

</script>

eLearnApps/Views/PeerFeedback/_PeerFeedback_Create.cshtml
@model eLearnApps.ViewModel.PeerFeedback.ManagePeerFeedbackModel
<style>
    .k-wizard-content { overflow: hidden; }

    .k-wizard-step {
        border: 1px solid #D4D4D4;
        overflow: hidden;
    }

    .k-step-text { overflow: visible; }

    .k-window-titlebar {
        background-color: #0e2669 !important;
        color: white;
    }

    .k-stepper .k-step-label .k-step-text { overflow: inherit; }
</style>
@Html.Partial("_PeerFeedback_CreateOrUpdateJs")
<form id="wizardForm" class="tab-form">
    @Html.AntiForgeryToken()
    <div class="card page-layout">
        <div class="card-header">
            <div class="row">
                <div class="col-12">
                    <h4 class="pl-2 mr-auto" id="cardHeaderTitle"> @(Model.Id.HasValue ? $"Edit - {Model.Name}" : "Add new")</h4>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="k-content">
                <div id="wizard"></div>
            </div>
        </div>
    </div>
    <span id="notification"></span>
</form>

<script>

    var evaluationId = 0,
        evaluationTypeId = 0,
        questionScoreCalculation = 0,
        notification,
        step = 0;
    const urlStep = "@Url.Action("PeerFeedbackStep", "PeerFeedback")?peerFeedbackId=@Model.Id.GetValueOrDefault()";
    const prevButton = { name: "previous", click: handleWizardSave };
    const nextButton = {
        name: "next",
        primary: false,
        click: function (e) {
            wizard.enableStep(1, true);
            var currentStep = wizard.activeStep();
            if (currentStep.options.index === 0) {
                if (!window.isValidForm()) {
                    wizard.enableStep(1, false);
                    e.preventDefault();
                }
            } else {
                NavigateByTagName('Manage');
            }
        }
    };
    const steps = [
        {
            title: "Properties",
            buttons: [nextButton],
            contentUrl: `${urlStep}&step=0`
        }, {
            title: "Sessions",
            buttons: [prevButton, nextButton],
            contentUrl: `${urlStep}&step=3`
        }
    ];
    var wizard = $("#wizard").kendoWizard({
        loadOnDemand: true,
        reloadOnSelect: true,
        steps: steps,
        pager: false,
        activate: function (e) {
            if (e.step.options.index === 1) {
                if (window.isValidForm()) {
                    $('button[data-action="save"]').click();
                }
                
            }
        }
    }).data("kendoWizard");

    $(document).ready(function() {
        notification = $("#notification").kendoNotification().data("kendoNotification");
    });
</script>